

#' @title Generate table of regression coefficients
#'
#' @name regcuttable
#' @param regcut list of regression coef data generated by .regcut function
#' @param covariate.labels a character vector of labels for covariates in regression tables. A value of NA for any element means that stargazer will print the corresponding variable name.
#' @param order a vector of numerical indexes that indicates the order in which variables will appear in the output.
#'
#' @return data.frame which contains regression coefficients
#'
#' @export

regcuttable <- function(regcut, covariate.labels = NULL, order = NULL) {

  var_name <- regcut %>%
    list.map(~c(.[,"variables"])) %>%
    list.cases()

  if (!is.null(order)) {var_name <- var_name[order]}

  var_merge <- data.frame(
    variables = rep(var_name, each = 2),
    stat = rep(c("coef", "s.e."), length(var_name)),
    stringsAsFactors = FALSE
  )

  coeftab <- regcut %>%
    list.map(~apply(var_merge, MARGIN = 1, function(x) .[.$variables == x[1] & .$stat == x[2], "value"])) %>%
    list.cbind()

  if (is.null(covariate.labels)) {
    name <- var_name %>%
      list.map(c(., "")) %>%
      unlist()
  } else {
    n1 <- length(var_name)
    n2 <- length(covariate.labels)

    if (n2 == n1) {
      name <- covariate.labels %>%
        list.map(c(., "")) %>%
        unlist()
    } else if (n2 < n1) {
      name <- c(covariate.labels, var_name[-(1:n2)])
      name <- name %>%
        list.map(c(., "")) %>%
        unlist()
    } else {
      name <- covariate.labels[1:n1] %>%
        list.map(c(., "")) %>%
        unlist()
    }
  }

  tab <- cbind(name, coeftab)
  rownames(tab) <- NULL

  return(tab)

}
